# Synthetic Monitoring Platform Configuration
monitoring:
  # Time interval between ping checks (in seconds)
  interval: 20
  
  # List of servers to monitor
  servers:
    - name: "Google DNS"
      host: "8.8.8.8"
      description: "Google Public DNS Server"
      
    - name: "Cloudflare DNS"
      host: "1.1.1.1"
      description: "Cloudflare Public DNS Server"