{
 "title": "Ping Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Packet Loss (8.8.8.8)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "packet_loss_count{server=\"8.8.8.8\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Packet Loss (1.1.1.1)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "packet_loss_count{server=\"1.1.1.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Round Trip Time",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 15, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_rtt{server=\"1.1.1.1\"}",
     "legendFormat": "Cloudflare (1.1.1.1)"
    },
    {
     "expr": "avg_rtt{server=\"8.8.8.8\"}",
     "legendFormat": "Google (8.8.8.8)"
    }
   ]
  }
 ]
}